/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.analyst.gui;

/**
 *
 * @author R1B3n
 */
public class FrPanel extends javax.swing.JPanel {

    /**
     * Creates new form FrPanel
     */
    public FrPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frNorthPanel = new javax.swing.JPanel();
        functionLabel = new javax.swing.JLabel();
        funcField = new javax.swing.JTextField();
        lowLabel = new javax.swing.JLabel();
        lowField = new javax.swing.JTextField();
        highLabel = new javax.swing.JLabel();
        highField = new javax.swing.JTextField();
        errorLabel = new javax.swing.JLabel();
        errorField = new javax.swing.JTextField();
        frCenterPanel = new javax.swing.JPanel();
        runButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        frSouthPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        frNorthPanel.setLayout(new javax.swing.BoxLayout(frNorthPanel, javax.swing.BoxLayout.LINE_AXIS));

        functionLabel.setFont(new java.awt.Font("Courier", 1, 24)); // NOI18N
        functionLabel.setForeground(new java.awt.Color(161, 131, 199));
        functionLabel.setText("Function:");
        frNorthPanel.add(functionLabel);

        funcField.setPreferredSize(new java.awt.Dimension(2000, 26));
        frNorthPanel.add(funcField);

        lowLabel.setFont(new java.awt.Font("Courier", 1, 24)); // NOI18N
        lowLabel.setForeground(new java.awt.Color(161, 131, 199));
        lowLabel.setText("Low:");
        frNorthPanel.add(lowLabel);
        frNorthPanel.add(lowField);

        highLabel.setFont(new java.awt.Font("Courier", 1, 24)); // NOI18N
        highLabel.setForeground(new java.awt.Color(161, 131, 199));
        highLabel.setText("High:");
        frNorthPanel.add(highLabel);
        frNorthPanel.add(highField);

        errorLabel.setFont(new java.awt.Font("Courier", 1, 24)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(161, 131, 199));
        errorLabel.setText("Tolerable Error:");
        frNorthPanel.add(errorLabel);
        frNorthPanel.add(errorField);

        add(frNorthPanel, java.awt.BorderLayout.PAGE_START);

        runButton.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        runButton.setForeground(new java.awt.Color(177, 191, 222));
        runButton.setText("Run");

        clearButton.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        clearButton.setForeground(new java.awt.Color(177, 191, 222));
        clearButton.setText("clear");

        javax.swing.GroupLayout frCenterPanelLayout = new javax.swing.GroupLayout(frCenterPanel);
        frCenterPanel.setLayout(frCenterPanelLayout);
        frCenterPanelLayout.setHorizontalGroup(
            frCenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frCenterPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(runButton)
                .addGap(18, 18, 18)
                .addComponent(clearButton)
                .addContainerGap(2495, Short.MAX_VALUE))
        );
        frCenterPanelLayout.setVerticalGroup(
            frCenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frCenterPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(frCenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(runButton)
                    .addComponent(clearButton))
                .addGap(20, 20, 20))
        );

        add(frCenterPanel, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout frSouthPanelLayout = new javax.swing.GroupLayout(frSouthPanel);
        frSouthPanel.setLayout(frSouthPanelLayout);
        frSouthPanelLayout.setHorizontalGroup(
            frSouthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2716, Short.MAX_VALUE)
        );
        frSouthPanelLayout.setVerticalGroup(
            frSouthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        add(frSouthPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private static javax.swing.JTextField errorField;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JPanel frCenterPanel;
    private javax.swing.JPanel frNorthPanel;
    private javax.swing.JPanel frSouthPanel;
    private static javax.swing.JTextField funcField;
    private javax.swing.JLabel functionLabel;
    private static javax.swing.JTextField highField;
    private javax.swing.JLabel highLabel;
    private static javax.swing.JTextField lowField;
    private javax.swing.JLabel lowLabel;
    private javax.swing.JButton runButton;
    // End of variables declaration//GEN-END:variables
}
