package com.analyst.gui;

import com.analyst.interpolation.Direct;
import com.analyst.interpolation.Lagrange;
import com.analyst.interpolation.NewtonsDividedDifference;
import com.analyst.sle.Gaussian;
import com.analyst.sle.LUDecomposition;
import com.analyst.sle.NaiveGaussian;
import java.awt.event.MouseEvent;
import java.util.Formatter;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author R1B3n
 */
public class InterpolationPanel extends javax.swing.JPanel {

    /**
     * Creates new form SlePanel
     */
    public InterpolationPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inpNorthPanel = new javax.swing.JPanel();
        inpComboBox = new javax.swing.JComboBox<>();
        inpCreateButton = new javax.swing.JButton();
        inputLabel = new javax.swing.JLabel();
        outputLabel = new javax.swing.JLabel();
        inpSouthPanel = new javax.swing.JPanel();
        runButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        unknownTextField = new javax.swing.JTextField();
        unknownLabel = new javax.swing.JLabel();
        inpSolnField = new javax.swing.JTextField();
        ipLabel = new javax.swing.JLabel();
        ipField = new javax.swing.JTextField();
        inpCenterPanel = new javax.swing.JPanel();
        matPanel = new javax.swing.JPanel();
        matScrollPane = new javax.swing.JScrollPane();
        matTable = new javax.swing.JTable();
        resPanel = new javax.swing.JPanel();
        resScrollPane = new javax.swing.JScrollPane();
        resTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        inpNorthPanel.setBackground(new java.awt.Color(0, 23, 39));

        inpComboBox.setForeground(new java.awt.Color(177, 191, 222));
        inpComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Direct method", "Lagrange's method", "Newton’s Divided Difference method" }));
        inpComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        inpCreateButton.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        inpCreateButton.setForeground(new java.awt.Color(177, 191, 222));
        inpCreateButton.setText("Create");
        inpCreateButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inpCreateButton.setPreferredSize(new java.awt.Dimension(110, 31));
        inpCreateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inpCreateButtonMouseClicked(evt);
            }
        });

        inputLabel.setFont(new java.awt.Font("Courier", 1, 24)); // NOI18N
        inputLabel.setForeground(new java.awt.Color(161, 131, 199));
        inputLabel.setText("Input:");

        outputLabel.setFont(new java.awt.Font("Courier", 1, 24)); // NOI18N
        outputLabel.setForeground(new java.awt.Color(161, 131, 199));
        outputLabel.setText("Output:");

        javax.swing.GroupLayout inpNorthPanelLayout = new javax.swing.GroupLayout(inpNorthPanel);
        inpNorthPanel.setLayout(inpNorthPanelLayout);
        inpNorthPanelLayout.setHorizontalGroup(
            inpNorthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inpNorthPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(inpComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(inputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(outputLabel)
                .addGap(100, 100, 100)
                .addComponent(inpCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        inpNorthPanelLayout.setVerticalGroup(
            inpNorthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inpNorthPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(inpNorthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inpComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inpNorthPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(inpNorthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputLabel)
                    .addComponent(outputLabel)))
        );

        add(inpNorthPanel, java.awt.BorderLayout.PAGE_START);

        inpSouthPanel.setBackground(new java.awt.Color(0, 23, 39));

        runButton.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        runButton.setForeground(new java.awt.Color(177, 191, 222));
        runButton.setText("Run");
        runButton.setEnabled(false);
        runButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        runButton.setMaximumSize(new java.awt.Dimension(93, 31));
        runButton.setMinimumSize(new java.awt.Dimension(93, 31));
        runButton.setPreferredSize(new java.awt.Dimension(93, 31));
        runButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                runButtonMouseClicked(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        clearButton.setForeground(new java.awt.Color(177, 191, 222));
        clearButton.setText("Clear");
        clearButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearButtonMouseClicked(evt);
            }
        });

        unknownTextField.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        unknownTextField.setForeground(new java.awt.Color(177, 191, 222));
        unknownTextField.setText("3");

        unknownLabel.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        unknownLabel.setForeground(new java.awt.Color(177, 191, 222));
        unknownLabel.setText("No. of data points:");

        inpSolnField.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        inpSolnField.setForeground(new java.awt.Color(108, 180, 64));
        inpSolnField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inpSolnField.setBorder(null);
        inpSolnField.setEditable(false);

        ipLabel.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        ipLabel.setForeground(new java.awt.Color(177, 191, 222));
        ipLabel.setText("Interpolation Point:");

        javax.swing.GroupLayout inpSouthPanelLayout = new javax.swing.GroupLayout(inpSouthPanel);
        inpSouthPanel.setLayout(inpSouthPanelLayout);
        inpSouthPanelLayout.setHorizontalGroup(
            inpSouthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inpSouthPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(runButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clearButton)
                .addGap(18, 18, 18)
                .addComponent(inpSolnField)
                .addGap(18, 18, 18)
                .addComponent(unknownLabel)
                .addGap(18, 18, 18)
                .addComponent(unknownTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ipLabel)
                .addGap(18, 18, 18)
                .addComponent(ipField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        inpSouthPanelLayout.setVerticalGroup(
            inpSouthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inpSouthPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(inpSouthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(runButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton)
                    .addComponent(unknownTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unknownLabel)
                    .addComponent(inpSolnField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ipLabel)
                    .addComponent(ipField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        add(inpSouthPanel, java.awt.BorderLayout.PAGE_END);

        inpCenterPanel.setBackground(new java.awt.Color(0, 23, 39));
        inpCenterPanel.setLayout(new java.awt.GridLayout(1, 0));

        matPanel.setBackground(new java.awt.Color(0, 23, 39));
        matPanel.setVisible(false);

        matTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(177, 191, 222), 3));
        matTable.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        matTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "X", "Y"
            }
        ));
        matTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        matTable.setFillsViewportHeight(true);
        matTable.setGridColor(new java.awt.Color(177, 191, 222));
        matTable.setRowSelectionAllowed(false);
        matTable.setShowGrid(true);
        matTable.getTableHeader().setReorderingAllowed(false);
        matScrollPane.setViewportView(matTable);
        if (matTable.getColumnModel().getColumnCount() > 0) {
            matTable.getColumnModel().getColumn(0).setResizable(false);
            matTable.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout matPanelLayout = new javax.swing.GroupLayout(matPanel);
        matPanel.setLayout(matPanelLayout);
        matPanelLayout.setHorizontalGroup(
            matPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(matPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(matScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))
        );
        matPanelLayout.setVerticalGroup(
            matPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(matScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
        );

        inpCenterPanel.add(matPanel);

        resPanel.setBackground(new java.awt.Color(0, 23, 39));
        resPanel.setVisible(false);

        resTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(177, 191, 222), 3));
        resTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        resTable.setFillsViewportHeight(true);
        resTable.setGridColor(new java.awt.Color(177, 191, 222));
        resTable.setRowSelectionAllowed(false);
        resTable.setShowGrid(true);
        resTable.getTableHeader().setReorderingAllowed(false);
        resScrollPane.setViewportView(resTable);

        javax.swing.GroupLayout resPanelLayout = new javax.swing.GroupLayout(resPanel);
        resPanel.setLayout(resPanelLayout);
        resPanelLayout.setHorizontalGroup(
            resPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        resPanelLayout.setVerticalGroup(
            resPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
        );

        inpCenterPanel.add(resPanel);

        add(inpCenterPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void inpCreateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inpCreateButtonMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            try {
                runButton.setEnabled(true);
                resPanel.setVisible(false);
                inpSolnField.setText("");
                int n = Integer.parseInt(unknownTextField.getText());
                if (n < 101 && n > 1) {
                    String[] title = new String[]{"X", "Y"};

                    DefaultTableModel modelMat = new DefaultTableModel(title, n);
                    title[0] = "Co-efficient no.";
                    title[1] = "Values";
                    DefaultTableModel modelRes = new DefaultTableModel(title, n);
                    matTable.setModel(modelMat);
                    resTable.setModel(modelRes);
                    matScrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_NEVER);
                    matPanel.setVisible(true);
                    repaint();
                } else {
                    JOptionPane.showMessageDialog(null,
                            "Valid input interval: [2, 100]",
                            "Warning!",
                            JOptionPane.WARNING_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,
                        "Invalid input",
                        "Error!",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_inpCreateButtonMouseClicked

    private void runButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_runButtonMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            JButton bt = (JButton) evt.getSource();
            if (!bt.isEnabled()) {
                return;
            }

            switch (inpComboBox.getSelectedIndex()) {
                case 0 ->
                    Direct.run();
                case 1 ->
                    Lagrange.run();
                case 2 ->
                    NewtonsDividedDifference.run();
            }
        }
    }//GEN-LAST:event_runButtonMouseClicked

    private void clearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            int n = Integer.parseInt(unknownTextField.getText());

            for (int i = 0; i < n; i++) {
                for (int j = 0; j < 2; j++) {
                    matTable.getModel().setValueAt(null, i, j);
                }
            }

            resPanel.setVisible(false);
            inpSolnField.setText("");
        }
    }//GEN-LAST:event_clearButtonMouseClicked

    public static int getNoOfUns() {
        return Integer.parseInt(unknownTextField.getText());
    }

    public static JTable getMat() {
        return matTable;
    }

    public static JTable getRes() {
        return resTable;
    }

    public static JPanel getResPanel() {
        return resPanel;
    }

    public static JTextField getsolnField() {
        return inpSolnField;
    }

    public static void setValue(double num, int i, int j) {
        Formatter formatter = new Formatter();
        if (j == 0) {
            formatter.format("%.0f", num);
        } else {
            formatter.format("%.5f", num);
        }
        resTable.getModel().setValueAt(formatter, i, j);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JPanel inpCenterPanel;
    public static javax.swing.JComboBox<String> inpComboBox;
    private javax.swing.JButton inpCreateButton;
    private javax.swing.JPanel inpNorthPanel;
    private static javax.swing.JTextField inpSolnField;
    private javax.swing.JPanel inpSouthPanel;
    private javax.swing.JLabel inputLabel;
    public static javax.swing.JTextField ipField;
    private javax.swing.JLabel ipLabel;
    private javax.swing.JPanel matPanel;
    private javax.swing.JScrollPane matScrollPane;
    private static javax.swing.JTable matTable;
    private javax.swing.JLabel outputLabel;
    private static javax.swing.JPanel resPanel;
    private javax.swing.JScrollPane resScrollPane;
    private static javax.swing.JTable resTable;
    private javax.swing.JButton runButton;
    private javax.swing.JLabel unknownLabel;
    private static javax.swing.JTextField unknownTextField;
    // End of variables declaration//GEN-END:variables
}
