package com.analyst.gui;

import com.analyst.integration.Simpsons;
import com.analyst.integration.Trapezoidal;
import java.awt.event.MouseEvent;
import javax.swing.JTextField;

/**
 *
 * @author R1B3n
 */
public class IntegrationPanel extends javax.swing.JPanel {

    /**
     * Creates new form IntegrationPanel
     */
    public IntegrationPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iNorthPanel = new javax.swing.JPanel();
        funcLabel = new javax.swing.JLabel();
        funcField = new javax.swing.JTextField();
        x0Label = new javax.swing.JLabel();
        x0Field = new javax.swing.JTextField();
        xnLabel = new javax.swing.JLabel();
        xnField = new javax.swing.JTextField();
        segLabel = new javax.swing.JLabel();
        segField = new javax.swing.JTextField();
        hLabel = new javax.swing.JLabel();
        hField = new javax.swing.JTextField();
        iCenterPanel = new javax.swing.JPanel();
        resPanel = new javax.swing.JPanel();
        resScrollPane = new javax.swing.JScrollPane();
        resTable = new javax.swing.JTable();
        iSouthPanel = new javax.swing.JPanel();
        runButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        iComboBox = new javax.swing.JComboBox<>();
        iSolnField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 23, 39));
        setLayout(new java.awt.BorderLayout());

        iNorthPanel.setPreferredSize(new java.awt.Dimension(978, 31));
        iNorthPanel.setLayout(new javax.swing.BoxLayout(iNorthPanel, javax.swing.BoxLayout.LINE_AXIS));

        funcLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        funcLabel.setForeground(new java.awt.Color(161, 131, 199));
        funcLabel.setText("Function:");
        iNorthPanel.add(funcLabel);

        funcField.setPreferredSize(new java.awt.Dimension(2000, 26));
        iNorthPanel.add(funcField);

        x0Label.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        x0Label.setForeground(new java.awt.Color(161, 131, 199));
        x0Label.setText("x₀:");
        iNorthPanel.add(x0Label);
        iNorthPanel.add(x0Field);

        xnLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        xnLabel.setForeground(new java.awt.Color(161, 131, 199));
        xnLabel.setText("xₙ:");
        iNorthPanel.add(xnLabel);
        iNorthPanel.add(xnField);

        segLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        segLabel.setForeground(new java.awt.Color(161, 131, 199));
        segLabel.setText("No. of segments:");
        iNorthPanel.add(segLabel);
        iNorthPanel.add(segField);

        hLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        hLabel.setForeground(new java.awt.Color(161, 131, 199));
        hLabel.setText("h: ");
        iNorthPanel.add(hLabel);

        hField.setBorder(null);
        hField.setEditable(false);
        iNorthPanel.add(hField);

        add(iNorthPanel, java.awt.BorderLayout.PAGE_START);

        iCenterPanel.setLayout(new java.awt.BorderLayout());

        resPanel.setVisible(false);
        resPanel.setLayout(new javax.swing.BoxLayout(resPanel, javax.swing.BoxLayout.LINE_AXIS));

        resTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        resTable.setFillsViewportHeight(true);
        resTable.setGridColor(new java.awt.Color(177, 191, 222));
        resTable.setRowSelectionAllowed(false);
        resTable.setShowGrid(true);
        resScrollPane.setViewportView(resTable);

        resPanel.add(resScrollPane);

        iCenterPanel.add(resPanel, java.awt.BorderLayout.CENTER);

        add(iCenterPanel, java.awt.BorderLayout.CENTER);

        iSouthPanel.setPreferredSize(new java.awt.Dimension(978, 66));

        runButton.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        runButton.setForeground(new java.awt.Color(177, 191, 222));
        runButton.setText("Run");
        runButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                runButtonMouseClicked(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        clearButton.setForeground(new java.awt.Color(177, 191, 222));
        clearButton.setText("Clear");
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearButtonMouseClicked(evt);
            }
        });

        iComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trapezoidal rule", "Simpson’s 1/3ʳᵈ rule" }));

        iSolnField.setForeground(new java.awt.Color(108, 180, 64));
        iSolnField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        iSolnField.setBorder(null);
        iSolnField.setEditable(false);

        javax.swing.GroupLayout iSouthPanelLayout = new javax.swing.GroupLayout(iSouthPanel);
        iSouthPanel.setLayout(iSouthPanelLayout);
        iSouthPanelLayout.setHorizontalGroup(
            iSouthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iSouthPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(runButton)
                .addGap(18, 18, 18)
                .addComponent(clearButton)
                .addGap(18, 18, 18)
                .addComponent(iSolnField, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(iComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        iSouthPanelLayout.setVerticalGroup(
            iSouthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, iSouthPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(iSouthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(runButton)
                    .addComponent(clearButton)
                    .addComponent(iComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iSolnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        add(iSouthPanel, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void runButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_runButtonMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            switch (iComboBox.getSelectedIndex()) {
                case 0 -> {
                    Trapezoidal.run();
                    if (Trapezoidal.flg && Trapezoidal.valid) {
                        resPanel.setVisible(true);
                    }
                }
                case 1 -> {
                    Simpsons.run();
                    if (Simpsons.flg && Simpsons.valid) {
                        resPanel.setVisible(true);
                    }
                }
            }
        }
    }//GEN-LAST:event_runButtonMouseClicked

    private void clearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            funcField.setText("");
            x0Field.setText("");
            xnField.setText("");
            segField.setText("");
            hField.setText("");
            iSolnField.setText("");
            resPanel.setVisible(false);
        }
    }//GEN-LAST:event_clearButtonMouseClicked

    public static JTextField getsolnField() {
        return iSolnField;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    public static javax.swing.JTextField funcField;
    private javax.swing.JLabel funcLabel;
    public static javax.swing.JTextField hField;
    private javax.swing.JLabel hLabel;
    private javax.swing.JPanel iCenterPanel;
    private javax.swing.JComboBox<String> iComboBox;
    private javax.swing.JPanel iNorthPanel;
    public static javax.swing.JTextField iSolnField;
    private javax.swing.JPanel iSouthPanel;
    private javax.swing.JPanel resPanel;
    private javax.swing.JScrollPane resScrollPane;
    public static javax.swing.JTable resTable;
    private javax.swing.JButton runButton;
    public static javax.swing.JTextField segField;
    private javax.swing.JLabel segLabel;
    public static javax.swing.JTextField x0Field;
    private javax.swing.JLabel x0Label;
    public static javax.swing.JTextField xnField;
    private javax.swing.JLabel xnLabel;
    // End of variables declaration//GEN-END:variables
}
