package com.analyst.gui;

import com.analyst.linearregression.LinearRegression;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.MouseEvent;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.Axis;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author R1B3n
 */
public class RegressionPanel extends javax.swing.JPanel {

    /**
     * Creates new form SlePanel
     */
    public RegressionPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lrNorthPanel = new javax.swing.JPanel();
        inputLabel = new javax.swing.JLabel();
        outputLabel = new javax.swing.JLabel();
        lrSouthPanel = new javax.swing.JPanel();
        runButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        unknownTextField = new javax.swing.JTextField();
        unknownLabel = new javax.swing.JLabel();
        inpSolnField = new javax.swing.JTextField();
        inpCreateButton = new javax.swing.JButton();
        lrCenterPanel = new javax.swing.JPanel();
        matPanel = new javax.swing.JPanel();
        matScrollPane = new javax.swing.JScrollPane();
        matTable = new javax.swing.JTable();
        resPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        lrNorthPanel.setBackground(new java.awt.Color(0, 23, 39));

        inputLabel.setFont(new java.awt.Font("Courier", 1, 24)); // NOI18N
        inputLabel.setForeground(new java.awt.Color(161, 131, 199));
        inputLabel.setText("Input:");

        outputLabel.setFont(new java.awt.Font("Courier", 1, 24)); // NOI18N
        outputLabel.setForeground(new java.awt.Color(161, 131, 199));
        outputLabel.setText("Output:");

        javax.swing.GroupLayout lrNorthPanelLayout = new javax.swing.GroupLayout(lrNorthPanel);
        lrNorthPanel.setLayout(lrNorthPanelLayout);
        lrNorthPanelLayout.setHorizontalGroup(
            lrNorthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lrNorthPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(inputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 778, Short.MAX_VALUE)
                .addComponent(outputLabel)
                .addGap(20, 20, 20))
        );
        lrNorthPanelLayout.setVerticalGroup(
            lrNorthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lrNorthPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(lrNorthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputLabel)
                    .addComponent(outputLabel))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        add(lrNorthPanel, java.awt.BorderLayout.PAGE_START);

        lrSouthPanel.setBackground(new java.awt.Color(0, 23, 39));

        runButton.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        runButton.setForeground(new java.awt.Color(177, 191, 222));
        runButton.setText("Run");
        runButton.setEnabled(false);
        runButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        runButton.setMaximumSize(new java.awt.Dimension(93, 31));
        runButton.setMinimumSize(new java.awt.Dimension(93, 31));
        runButton.setPreferredSize(new java.awt.Dimension(93, 31));
        runButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                runButtonMouseClicked(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        clearButton.setForeground(new java.awt.Color(177, 191, 222));
        clearButton.setText("Clear");
        clearButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearButtonMouseClicked(evt);
            }
        });

        unknownTextField.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        unknownTextField.setForeground(new java.awt.Color(177, 191, 222));
        unknownTextField.setText("3");

        unknownLabel.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        unknownLabel.setForeground(new java.awt.Color(177, 191, 222));
        unknownLabel.setText("No. of data points:");

        inpSolnField.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        inpSolnField.setForeground(new java.awt.Color(108, 180, 64));
        inpSolnField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inpSolnField.setBorder(null);
        inpSolnField.setEditable(false);

        inpCreateButton.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        inpCreateButton.setForeground(new java.awt.Color(177, 191, 222));
        inpCreateButton.setText("Create");
        inpCreateButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inpCreateButton.setPreferredSize(new java.awt.Dimension(110, 31));
        inpCreateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inpCreateButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout lrSouthPanelLayout = new javax.swing.GroupLayout(lrSouthPanel);
        lrSouthPanel.setLayout(lrSouthPanelLayout);
        lrSouthPanelLayout.setHorizontalGroup(
            lrSouthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lrSouthPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(runButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clearButton)
                .addGap(18, 18, 18)
                .addComponent(inpSolnField, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(unknownLabel)
                .addGap(18, 18, 18)
                .addComponent(unknownTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inpCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        lrSouthPanelLayout.setVerticalGroup(
            lrSouthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lrSouthPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(lrSouthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(runButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton)
                    .addComponent(unknownTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unknownLabel)
                    .addComponent(inpSolnField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        add(lrSouthPanel, java.awt.BorderLayout.PAGE_END);

        lrCenterPanel.setBackground(new java.awt.Color(0, 23, 39));
        lrCenterPanel.setLayout(new java.awt.GridLayout(1, 0));

        matPanel.setBackground(new java.awt.Color(0, 23, 39));
        matPanel.setVisible(false);

        matTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(177, 191, 222), 3));
        matTable.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        matTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "X", "Y"
            }
        ));
        matTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        matTable.setFillsViewportHeight(true);
        matTable.setGridColor(new java.awt.Color(177, 191, 222));
        matTable.setRowSelectionAllowed(false);
        matTable.setShowGrid(true);
        matTable.getTableHeader().setReorderingAllowed(false);
        matScrollPane.setViewportView(matTable);
        if (matTable.getColumnModel().getColumnCount() > 0) {
            matTable.getColumnModel().getColumn(0).setResizable(false);
            matTable.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout matPanelLayout = new javax.swing.GroupLayout(matPanel);
        matPanel.setLayout(matPanelLayout);
        matPanelLayout.setHorizontalGroup(
            matPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(matPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(matScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))
        );
        matPanelLayout.setVerticalGroup(
            matPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(matScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
        );

        lrCenterPanel.add(matPanel);

        resPanel.setBackground(new java.awt.Color(0, 23, 39));
        resPanel.setVisible(false);
        resPanel.setLayout(new java.awt.BorderLayout());
        lrCenterPanel.add(resPanel);

        add(lrCenterPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void inpCreateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inpCreateButtonMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            try {
                runButton.setEnabled(true);
                resPanel.setVisible(false);
                inpSolnField.setText("");
                int n = Integer.parseInt(unknownTextField.getText());
                if (n < 101 && n > 1) {
                    String[] title = new String[]{"X", "Y"};

                    DefaultTableModel modelMat = new DefaultTableModel(title, n);
                    DefaultTableModel modelRes = new DefaultTableModel(title, n);
                    matTable.setModel(modelMat);
                    matScrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_NEVER);
                    matPanel.setVisible(true);
                    repaint();
                } else {
                    JOptionPane.showMessageDialog(null,
                            "Valid input interval: [2, 100]",
                            "Warning!",
                            JOptionPane.WARNING_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,
                        "Invalid input",
                        "Error!",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_inpCreateButtonMouseClicked

    private void runButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_runButtonMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            JButton bt = (JButton) evt.getSource();
            if (!bt.isEnabled()) {
                return;
            }
            resPanel.setVisible(false);
            resPanel.removeAll();
            LinearRegression.run();
            resPanel.setVisible(true);
        }
    }//GEN-LAST:event_runButtonMouseClicked

    private void clearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            int n = Integer.parseInt(unknownTextField.getText());

            for (int i = 0; i < n; i++) {
                for (int j = 0; j < 2; j++) {
                    matTable.getModel().setValueAt(null, i, j);
                }
            }

            resPanel.setVisible(false);
            inpSolnField.setText("");
        }
    }//GEN-LAST:event_clearButtonMouseClicked

    public static int getNoOfUns() {
        return Integer.parseInt(unknownTextField.getText());
    }

    public static JTable getMat() {
        return matTable;
    }

    public static JPanel getResPanel() {
        return resPanel;
    }

    public static JTextField getsolnField() {
        return inpSolnField;
    }

    public static void plotModel(double mata[], double matb[], double slp, double icp, int n) {
        XYSeriesCollection dataset = new XYSeriesCollection();
        XYSeries series1 = new XYSeries("Original points");
        XYSeries series2 = new XYSeries("Regression line");
        for (int i = 0; i <= n; i++) {
            series1.add(mata[i], matb[i]);
            series2.add(mata[i], icp + slp * mata[i]);
        }
        dataset.addSeries(series1);
        dataset.addSeries(series2);

        JFreeChart chart = ChartFactory.createXYLineChart("Linear Regression Model",
                "X-Axis", "Y-Axis", dataset);
        chart.setBackgroundPaint(new Color(0, 23, 39));
        chart.getTitle().setPaint(new Color(161, 131, 199));

        XYPlot plot = (XYPlot) chart.getPlot();
        plot.setBackgroundPaint(new Color(0, 23, 39));
        setAxisFontColor(((XYPlot) plot).getDomainAxis(), new Color(177, 191, 222));
        setAxisFontColor(((XYPlot) plot).getRangeAxis(), new Color(177, 191, 222));

        XYLineAndShapeRenderer renderer = (XYLineAndShapeRenderer) plot.getRenderer();
        renderer.setSeriesLinesVisible(0, false);
        renderer.setSeriesShapesVisible(0, true);
        renderer.setSeriesLinesVisible(1, true);
        renderer.setSeriesShapesVisible(1, false);

        ChartPanel panel = new ChartPanel(chart);
        panel.setBackground(new Color(0, 23, 39));

        resPanel.add(panel, BorderLayout.CENTER);
    }

    private static void setAxisFontColor(Axis axis, Color fontColor) {
        if (!fontColor.equals(axis.getLabelPaint())) {
            axis.setLabelPaint(fontColor);
        }
        if (!fontColor.equals(axis.getTickLabelPaint())) {
            axis.setTickLabelPaint(fontColor);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JButton inpCreateButton;
    private static javax.swing.JTextField inpSolnField;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JPanel lrCenterPanel;
    private javax.swing.JPanel lrNorthPanel;
    private javax.swing.JPanel lrSouthPanel;
    private javax.swing.JPanel matPanel;
    private javax.swing.JScrollPane matScrollPane;
    private static javax.swing.JTable matTable;
    private javax.swing.JLabel outputLabel;
    private static javax.swing.JPanel resPanel;
    private javax.swing.JButton runButton;
    private javax.swing.JLabel unknownLabel;
    private static javax.swing.JTextField unknownTextField;
    // End of variables declaration//GEN-END:variables
}
